(() => {
  'use strict';
  const TF=window.TwoFly;let balances=[],reconciliations=[],rows=[],timer;
  const fmt=v=>TF.money(TF.num(v));const date=v=>v?String(v).slice(0,10):'—';
  async function load(){try{const [a,b]=await Promise.all([TF.state.supa.from('v_cash_account_balances').select('*').eq('active',true).order('name'),TF.state.supa.from('v_cash_reconciliations_v13').select('*').order('reconciled_at',{ascending:false}).limit(500)]);if(a.error||b.error)throw a.error||b.error;balances=a.data||[];reconciliations=b.data||[];fillAccounts();renderCash();await search();}catch(e){TF.fail(e,'Cash check failed');}}
  function latest(accountId){return reconciliations.find(x=>x.cash_account_id===accountId);}
  function fillAccounts(){const current=TF.$('reconcileAccount').value;TF.$('reconcileAccount').innerHTML='<option value="">Select account</option>'+balances.map(x=>`<option value="${x.id}">${TF.esc(x.name)} — system ${fmt(x.current_balance)}</option>`).join('');if(current)TF.$('reconcileAccount').value=current;}
  function renderCash(){TF.$('cashTable').innerHTML=`<table><thead><tr><th>Account</th><th>System balance</th><th>Latest actual</th><th>Difference</th><th>Checked</th><th>Notes</th></tr></thead><tbody>${balances.map(x=>{const r=latest(x.id),diff=r?TF.num(r.difference):null;return `<tr><td><strong>${TF.esc(x.name)}</strong><br><small>${TF.esc(x.account_type)}</small></td><td>${fmt(x.current_balance)}</td><td>${r?fmt(r.actual_balance):'Not checked'}</td><td>${r?`<strong class="${Math.abs(diff)<.01?'text-ok':'text-danger'}">${fmt(diff)}</strong>`:'—'}</td><td>${r?`${date(r.reconciliation_date)}<br><small>${new Date(r.reconciled_at).toLocaleString('en-PH')}</small>`:'—'}</td><td>${TF.esc(r?.notes||'')}</td></tr>`}).join('')}</tbody></table>`;updatePreview();}
  function updatePreview(){const a=balances.find(x=>x.id===TF.$('reconcileAccount').value),actual=TF.num(TF.$('reconcileActual').value);TF.$('reconcilePreview').textContent=a?`System ${fmt(a.current_balance)} · actual ${fmt(actual)} · difference ${fmt(actual-TF.num(a.current_balance))}`:'Select an account.';}
  async function save(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const r=await TF.state.supa.rpc('record_cash_reconciliation_v13',{p_reconciliation_date:TF.$('reconcileDate').value,p_cash_account_id:TF.$('reconcileAccount').value,p_actual_balance:TF.num(TF.$('reconcileActual').value),p_notes:TF.$('reconcileNotes').value.trim()});if(r.error)throw r.error;TF.toast('Cash check saved');e.target.reset();TF.$('reconcileDate').value=TF.today();await load();}catch(err){TF.fail(err,'Cash check not saved');}finally{TF.setLoading(b,false);}}
  async function search(){try{const term=TF.$('transactionSearch').value.trim().replaceAll('₱','').replaceAll(',','');let q=TF.state.supa.from('v_transaction_search_v13').select('*').order('activity_date',{ascending:false}).limit(250);if(term)q=q.ilike('search_text',`%${term.replaceAll('%','')}%`);const r=await q;if(r.error)throw r.error;rows=r.data||[];renderRows();}catch(e){TF.fail(e,'Search failed');}}
  function renderRows(){TF.$('transactionTable').innerHTML=`<table><thead><tr><th>Date</th><th>Record</th><th>Title / party</th><th>Amount or balance</th><th>Account</th><th>Status</th><th>Reference</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${date(x.activity_date)}</td><td>${TF.esc(x.record_type)}</td><td><strong>${TF.esc(x.title)}</strong><br><small>${TF.esc(x.party||'')}</small></td><td>${fmt(x.amount)}</td><td>${TF.esc(x.account_name||'—')}</td><td>${TF.statusPill(x.status)}</td><td><small>${TF.esc(x.reference_table||'')} ${TF.esc(x.reference_id||'')}</small></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No matching records.</td></tr>'}</tbody></table>`;}
  TF.ready.then(()=>{TF.$('reconcileDate').value=TF.today();TF.$('reconcileForm').addEventListener('submit',save);TF.$('reconcileAccount').addEventListener('change',updatePreview);TF.$('reconcileActual').addEventListener('input',updatePreview);TF.$('transactionSearch').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(search,250)});window.addEventListener('twofly:refresh',load);load();}).catch(e=>TF.fail(e,'Cash check failed'));
})();
