(() => {
  'use strict';const TF=window.TwoFly;
  const categories={
    business:['Staff salary','Packaging','Ads','Rent','Electricity','Internet','Office supplies','Software','Transportation','Food for staff','Repairs','Transaction fees','Other business expense'],
    personal:['Food','Coffee','Gym','Personal transportation','Clothes','Wants','Family','Personal bills','Personal savings','Other personal expense'],
    refund:['Customer refund','Order adjustment','Shipping refund','Other refund'],
    loss:['Missing item','Damaged product','Courier loss','Unrecoverable parcel','Inventory loss','Other business loss'],
    asset:['Sewing machine','Computer','Printer','Shelving','Store equipment','Business phone','Other business asset']
  };
  function fill(){TF.$('expenseDate').value=TF.today();TF.$('expenseMonth').value=TF.monthKey();TF.$('expenseAccount').innerHTML=TF.accountOptions(false);if(!TF.isOwner()){TF.$('personalOption').disabled=true;}updateType();}
  function updateType(){const type=TF.$('expenseEntryType').value;TF.$('expenseCategory').innerHTML=(categories[type]||[]).map(x=>`<option value="${TF.esc(x)}">${TF.esc(x)}</option>`).join('');TF.$('expenseOrderWrap').classList.toggle('hidden',type!=='refund');const messages={business:'Reduces cash and business profit.',personal:'Reduces cash and owner-pay remaining, but does not reduce business profit.',refund:'Reduces cash and profit. Link the related order when possible.',loss:'Reduces cash and profit as a business loss.',asset:'Reduces cash but stays separate from daily operating expenses.'};TF.$('expenseEffect').textContent=messages[type]||'';}
  async function loadOrders(){const {data,error}=await TF.state.supa.from('orders').select('id,order_number,customer_name').order('created_at',{ascending:false}).limit(1000);if(error)throw error;TF.$('expenseOrder').innerHTML='<option value="">No linked order</option>'+(data||[]).map(o=>`<option value="${o.id}">${TF.esc(o.order_number)} — ${TF.esc(o.customer_name)}</option>`).join('');}
  async function save(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const type=TF.$('expenseEntryType').value;const {error}=await TF.state.supa.rpc('record_expense_v5',{p_date:TF.$('expenseDate').value,p_entry_type:type,p_category:TF.$('expenseCategory').value,p_amount:TF.num(TF.$('expenseAmount').value),p_cash_account_id:TF.$('expenseAccount').value,p_payee:TF.$('expensePayee').value.trim(),p_related_order_id:type==='refund'?(TF.$('expenseOrder').value||null):null,p_notes:TF.$('expenseNotes').value.trim()});if(error)throw error;TF.toast(type==='personal'?'Personal expense recorded as owner draw':'Expense recorded');e.target.reset();fill();await load();}catch(err){TF.fail(err,'Record not saved');}finally{TF.setLoading(b,false);}}
  async function load(){try{const m=TF.$('expenseMonth').value||TF.monthKey(),start=m+'-01',end=TF.monthEndExclusive(m);const [eR,dR]=await Promise.all([TF.state.supa.from('expenses').select('*,orders(order_number)').gte('expense_date',start).lt('expense_date',end).order('expense_date',{ascending:false}),TF.isOwner()?TF.state.supa.from('owner_draws').select('*').gte('draw_date',start).lt('draw_date',end).order('draw_date',{ascending:false}):Promise.resolve({data:[],error:null})]);if(eR.error||dR.error)throw eR.error||dR.error;const rows=eR.data||[],draws=dR.data||[];const sums={operating:0,refund:0,loss:0,asset:0,personal:0};rows.forEach(x=>sums[x.expense_type]=(sums[x.expense_type]||0)+TF.num(x.amount));draws.forEach(x=>sums.personal+=TF.num(x.amount));TF.$('expenseSummary').innerHTML=`<div class="totals-panel"><div><span>Business operating</span><strong>${TF.money(sums.operating)}</strong></div><div><span>Refunds + losses</span><strong>${TF.money(sums.refund+sums.loss)}</strong></div><div><span>Equipment / assets</span><strong>${TF.money(sums.asset)}</strong></div><div class="owner-only"><span>Personal / owner draws</span><strong>${TF.money(sums.personal)}</strong></div></div>`;TF.$('expensesTable').innerHTML=`<table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Payee</th><th>Order</th><th>Amount</th><th>Notes</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${TF.esc(x.expense_date)}</td><td>${TF.esc(x.expense_type)}</td><td>${TF.esc(x.category)}</td><td>${TF.esc(x.supplier||'—')}</td><td>${TF.esc(x.orders?.order_number||'—')}</td><td>${TF.money(x.amount)}</td><td>${TF.esc(x.notes||'')}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No business expenses.</td></tr>'}</tbody></table>`;if(TF.isOwner())TF.$('personalTable').innerHTML=`<table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Notes</th></tr></thead><tbody>${draws.map(x=>`<tr><td>${TF.esc(x.draw_date)}</td><td>${TF.esc(String(x.draw_type).replaceAll('_',' '))}</td><td>${TF.money(x.amount)}</td><td>${TF.esc(x.notes||'')}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No personal expenses.</td></tr>'}</tbody></table>`;}catch(e){TF.fail(e,'Expenses failed');}}
  TF.ready.then(async()=>{fill();await loadOrders();TF.$('expenseEntryType').addEventListener('change',updateType);TF.$('expenseForm').addEventListener('submit',save);TF.$('expenseMonth').addEventListener('change',load);window.addEventListener('twofly:refresh',load);load();}).catch(e=>TF.fail(e,'Expenses failed'));
})();
