(() => {
  'use strict';
  const TF=window.TwoFly;let batches=[];
  function fill(){
    const cats=TF.categoryOptions(),acc=TF.accountOptions(true);TF.$('ownBatchCategory').innerHTML=cats;TF.$('subconCategory').innerHTML=cats;['ownBatchAccount','pulloutAccount','subconAccount'].forEach(id=>TF.$(id).innerHTML=acc);
    TF.$('ownBatchDate').value=TF.today();TF.$('pulloutDate').value=TF.today();TF.$('subconDate').value=TF.today();TF.$('ownCutRate').value=TF.state.settings.default_cutting_rate;TF.$('ownSewerRate').value=TF.state.settings.default_sewer_rate;TF.$('pulloutSewerRate').value=TF.state.settings.default_sewer_rate;
  }
  async function load(){
    try{const {data,error}=await TF.state.supa.from('production_batches').select('*,inventory_categories(code,name)').order('created_at',{ascending:false}).limit(200);if(error)throw error;batches=data||[];TF.$('pulloutBatch').innerHTML='<option value="">Select batch</option>'+batches.filter(b=>b.source_type==='own_production'&&!['completed','cancelled'].includes(b.status)).map(b=>`<option value="${b.id}">${TF.esc(b.batch_number)} — ${TF.esc(b.inventory_categories.name)}</option>`).join('');TF.$('productionTable').innerHTML=`<table><thead><tr><th>Batch</th><th>Source</th><th>Category</th><th>Status</th><th>Cut / Good / Reject</th><th>Total cost</th><th>Unit cost</th><th>Payable</th></tr></thead><tbody>${batches.map(b=>`<tr><td><strong>${TF.esc(b.batch_number)}</strong><br><small>${TF.esc(b.start_date)}</small></td><td>${TF.esc(b.source_type.replaceAll('_',' '))}</td><td>${TF.esc(b.inventory_categories.name)}</td><td>${TF.statusPill(b.status)}</td><td>${TF.num(b.cut_quantity)} / ${TF.num(b.good_finished_quantity)} / ${TF.num(b.rejected_quantity)}</td><td>${TF.money(b.total_batch_cost)}</td><td>${TF.money(b.final_unit_cost)}</td><td>${TF.esc(b.payable_status)}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">No production batches.</td></tr>'}</tbody></table>`;}catch(e){TF.fail(e,'Production failed');}
  }
  async function own(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const {error}=await TF.state.supa.rpc('create_own_production_batch',{p_batch_number:TF.$('ownBatchNumber').value.trim(),p_category_code:TF.$('ownBatchCategory').value,p_start_date:TF.$('ownBatchDate').value,p_fabric_cost_used:Number(TF.$('ownFabricCost').value||0),p_cut_quantity:Number(TF.$('ownCutQty').value),p_cutting_rate:Number(TF.$('ownCutRate').value),p_garter_quantity_used:Number(TF.$('ownGarterQty').value||0),p_default_sewer_rate:Number(TF.$('ownSewerRate').value),p_cash_account_id:TF.$('ownBatchAccount').value||null,p_notes:TF.$('ownBatchNotes').value.trim()});if(error)throw error;TF.toast('Production batch created and exact garters deducted');e.target.reset();fill();await load();}catch(err){TF.fail(err,'Batch not created');}finally{TF.setLoading(b,false);}}
  async function pullout(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const dist=Object.entries(TF.parseLinesMap(TF.$('pulloutDistribution').value)).map(([sku,quantity])=>({sku,quantity}));const {error}=await TF.state.supa.rpc('add_production_pullout',{p_batch_id:TF.$('pulloutBatch').value,p_pullout_date:TF.$('pulloutDate').value,p_completed_quantity:Number(TF.$('pulloutQty').value),p_sewer_rate:Number(TF.$('pulloutSewerRate').value),p_distribution:dist,p_cash_account_id:TF.$('pulloutAccount').value||null,p_final_pullout:TF.$('pulloutFinal').checked,p_rejected_quantity:Number(TF.$('pulloutRejects').value||0),p_notes:TF.$('pulloutNotes').value.trim()});if(error)throw error;TF.toast('Pullout added to finished inventory');e.target.reset();fill();await load();}catch(err){TF.fail(err,'Pullout not saved');}finally{TF.setLoading(b,false);}}
  async function subcon(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const dist=Object.entries(TF.parseLinesMap(TF.$('subconDistribution').value)).map(([sku,quantity])=>({sku,quantity}));const {error}=await TF.state.supa.rpc('receive_subcon_batch',{p_batch_number:TF.$('subconBatchNumber').value.trim(),p_category_code:TF.$('subconCategory').value,p_received_date:TF.$('subconDate').value,p_partner_name:TF.$('subconPartner').value.trim(),p_quantity:Number(TF.$('subconQty').value),p_price_per_piece:Number(TF.$('subconPrice').value),p_handling_cost:Number(TF.$('subconHandling').value||0),p_amount_paid:Number(TF.$('subconPaid').value||0),p_distribution:dist,p_cash_account_id:TF.$('subconAccount').value||null,p_notes:TF.$('subconNotes').value.trim()});if(error)throw error;TF.toast('Subcon finished goods received');e.target.reset();fill();await load();}catch(err){TF.fail(err,'Subcon receipt failed');}finally{TF.setLoading(b,false);}}
  TF.ready.then(()=>{fill();TF.$('ownBatchForm').addEventListener('submit',own);TF.$('pulloutForm').addEventListener('submit',pullout);TF.$('subconForm').addEventListener('submit',subcon);window.addEventListener('twofly:refresh',load);load();}).catch(e=>TF.fail(e,'Production failed'));
})();
