(() => {
  'use strict';
  const TF=window.TwoFly;let batches=[],payables=[],fabric=[];
  function fill(){
    const cats=TF.categoryOptions(),accounts=TF.accountOptions(false);
    TF.$('ownBatchCategory').innerHTML=cats;TF.$('subconCategory').innerHTML=cats;
    ['fabricAccount','pulloutAccount','subconAccount','payPayableAccount'].forEach(id=>TF.$(id).innerHTML=accounts);
    ['fabricDate','ownBatchDate','pulloutDate','subconDate','payPayableDate'].forEach(id=>TF.$(id).value=TF.today());
    TF.$('ownCutRate').value=TF.state.settings.default_cutting_rate;TF.$('ownSewerRate').value=TF.state.settings.default_sewer_rate;TF.$('pulloutSewerRate').value=TF.state.settings.default_sewer_rate;
    updatePaymentFields();updateSummaries();
  }
  function updatePaymentFields(){
    TF.$('pulloutAccountWrap').classList.toggle('field-disabled',TF.num(TF.$('pulloutPaid').value)<=0);
    TF.$('pulloutAccount').disabled=TF.num(TF.$('pulloutPaid').value)<=0;
    TF.$('subconAccountWrap').classList.toggle('field-disabled',TF.num(TF.$('subconPaid').value)<=0);
    TF.$('subconAccount').disabled=TF.num(TF.$('subconPaid').value)<=0;
  }
  function updateSummaries(){
    const q=TF.num(TF.$('pulloutQty').value),rate=TF.num(TF.$('pulloutSewerRate').value),paid=TF.num(TF.$('pulloutPaid').value),due=q*rate;
    TF.$('pulloutSummary').textContent=q?`Sewer pay: ${TF.money(due)} · Paid now: ${TF.money(paid)} · Payable: ${TF.money(Math.max(due-paid,0))}`:'Enter completed pieces to calculate sewer pay.';
    const sq=TF.num(TF.$('subconQty').value),price=TF.num(TF.$('subconPrice').value),handling=TF.num(TF.$('subconHandling').value),spaid=TF.num(TF.$('subconPaid').value),total=sq*price+handling;
    TF.$('subconSummary').textContent=sq&&price?`Total landed cost: ${TF.money(total)} · Paid now: ${TF.money(spaid)} · Payable: ${TF.money(Math.max(total-spaid,0))}`:'Enter quantity and price to see the total cost.';
  }
  async function load(){
    try{
      const [bR,pR,fR]=await Promise.all([
        TF.state.supa.from('production_batches').select('*,inventory_categories(code,name)').order('created_at',{ascending:false}).limit(300),
        TF.state.supa.from('payables').select('*').neq('status','paid').order('payable_date',{ascending:false}),
        TF.state.supa.from('fabric_purchases').select('*').order('purchase_date',{ascending:false})
      ]);if(bR.error||pR.error||fR.error)throw bR.error||pR.error||fR.error;
      batches=bR.data||[];payables=pR.data||[];fabric=fR.data||[];
      TF.$('pulloutBatch').innerHTML='<option value="">Select batch</option>'+batches.filter(b=>b.source_type==='own_production'&&!['completed','cancelled'].includes(b.status)).map(b=>`<option value="${b.id}">${TF.esc(b.batch_number)} — ${TF.esc(b.inventory_categories.name)}</option>`).join('');
      TF.$('ownFabricPurchase').innerHTML='<option value="">Manual fabric value / no linked purchase</option>'+fabric.filter(f=>TF.num(f.total_cost)>TF.num(f.allocated_cost)).map(f=>`<option value="${f.id}">${TF.esc(f.purchase_date)} — ${TF.esc(f.supplier||'No supplier')} — remaining ${TF.money(TF.num(f.total_cost)-TF.num(f.allocated_cost))}</option>`).join('');
      TF.$('productionTable').innerHTML=`<table><thead><tr><th>Batch</th><th>Source</th><th>Category</th><th>Status</th><th>Cut / Good / Reject</th><th>Total cost</th><th>Unit cost</th><th>Payment</th></tr></thead><tbody>${batches.map(b=>`<tr><td><strong>${TF.esc(b.batch_number)}</strong><br><small>${TF.esc(b.start_date)}</small></td><td>${TF.esc(String(b.source_type).replaceAll('_',' '))}</td><td>${TF.esc(b.inventory_categories?.name||'')}</td><td>${TF.statusPill(b.status)}</td><td>${TF.num(b.cut_quantity)} / ${TF.num(b.good_finished_quantity)} / ${TF.num(b.rejected_quantity)}</td><td>${TF.money(b.total_batch_cost)}</td><td>${TF.money(b.final_unit_cost)}</td><td>${TF.esc(b.payable_status)}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">No production batches.</td></tr>'}</tbody></table>`;
      TF.$('payablesTable').innerHTML=`<table><thead><tr><th>Date</th><th>Type</th><th>Party</th><th>Due</th><th>Paid</th><th>Remaining</th><th></th></tr></thead><tbody>${payables.map(p=>`<tr><td>${TF.esc(p.payable_date)}</td><td>${TF.esc(p.payable_type)}</td><td>${TF.esc(p.party_name)}</td><td>${TF.money(p.amount_due)}</td><td>${TF.money(p.amount_paid)}</td><td><strong>${TF.money(TF.num(p.amount_due)-TF.num(p.amount_paid))}</strong></td><td><button class="btn primary small" data-pay="${p.id}">Pay</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No open payables.</td></tr>'}</tbody></table>`;
      TF.$('fabricTable').innerHTML=`<table><thead><tr><th>Date</th><th>Supplier</th><th>Description</th><th>Total cost</th><th>Allocated</th><th>Remaining</th></tr></thead><tbody>${fabric.map(f=>`<tr><td>${TF.esc(f.purchase_date)}</td><td>${TF.esc(f.supplier||'—')}</td><td>${TF.esc(f.description||'')}</td><td>${TF.money(f.total_cost)}</td><td>${TF.money(f.allocated_cost)}</td><td>${TF.money(TF.num(f.total_cost)-TF.num(f.allocated_cost))}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No fabric purchases.</td></tr>'}</tbody></table>`;
    }catch(e){TF.fail(e,'Production failed');}
  }
  async function saveFabric(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const {error}=await TF.state.supa.rpc('record_fabric_purchase_v5',{p_purchase_date:TF.$('fabricDate').value,p_supplier:TF.$('fabricSupplier').value.trim(),p_description:TF.$('fabricDescription').value.trim(),p_total_cost:TF.num(TF.$('fabricCost').value),p_cash_account_id:TF.$('fabricAccount').value,p_notes:TF.$('fabricNotes').value.trim()});if(error)throw error;TF.toast('Fabric purchase recorded');e.target.reset();TF.$('fabricDate').value=TF.today();await load();}catch(err){TF.fail(err,'Fabric purchase not saved');}finally{TF.setLoading(b,false);}}
  async function own(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const {error}=await TF.state.supa.rpc('create_own_production_batch_v5',{p_batch_number:TF.$('ownBatchNumber').value.trim(),p_category_code:TF.$('ownBatchCategory').value,p_start_date:TF.$('ownBatchDate').value,p_fabric_purchase_id:TF.$('ownFabricPurchase').value||null,p_fabric_cost_used:TF.num(TF.$('ownFabricCost').value),p_cut_quantity:TF.num(TF.$('ownCutQty').value),p_cutting_rate:TF.num(TF.$('ownCutRate').value),p_garter_quantity_used:TF.num(TF.$('ownGarterQty').value),p_default_sewer_rate:TF.num(TF.$('ownSewerRate').value),p_notes:TF.$('ownBatchNotes').value.trim()});if(error)throw error;TF.toast('Production batch created; cutting balance added to Payables');e.target.reset();fill();await load();}catch(err){TF.fail(err,'Batch not created');}finally{TF.setLoading(b,false);}}
  async function pullout(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const paid=TF.num(TF.$('pulloutPaid').value);const {error}=await TF.state.supa.rpc('add_production_pullout_v5',{p_batch_id:TF.$('pulloutBatch').value,p_pullout_date:TF.$('pulloutDate').value,p_completed_quantity:TF.num(TF.$('pulloutQty').value),p_sewer_rate:TF.num(TF.$('pulloutSewerRate').value),p_amount_paid:paid,p_cash_account_id:paid>0?TF.$('pulloutAccount').value:null,p_final_pullout:TF.$('pulloutFinal').checked,p_rejected_quantity:TF.num(TF.$('pulloutRejects').value),p_notes:TF.$('pulloutNotes').value.trim()});if(error)throw error;TF.toast('Pullout added to category inventory');e.target.reset();fill();await load();}catch(err){TF.fail(err,'Pullout not saved');}finally{TF.setLoading(b,false);}}
  async function subcon(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const paid=TF.num(TF.$('subconPaid').value);const {error}=await TF.state.supa.rpc('receive_subcon_batch_v5',{p_batch_number:TF.$('subconBatchNumber').value.trim(),p_category_code:TF.$('subconCategory').value,p_received_date:TF.$('subconDate').value,p_partner_name:TF.$('subconPartner').value.trim(),p_quantity:TF.num(TF.$('subconQty').value),p_price_per_piece:TF.num(TF.$('subconPrice').value),p_handling_cost:TF.num(TF.$('subconHandling').value),p_amount_paid:paid,p_cash_account_id:paid>0?TF.$('subconAccount').value:null,p_notes:TF.$('subconNotes').value.trim()});if(error)throw error;TF.toast('Subcon inventory received');e.target.reset();fill();await load();}catch(err){TF.fail(err,'Subcon receipt failed');}finally{TF.setLoading(b,false);}}
  function openPay(id){const p=payables.find(x=>x.id===id);if(!p)return;TF.$('payPayableId').value=id;TF.$('payPayableTitle').textContent=`Pay ${p.payable_type}`;TF.$('payPayableMeta').textContent=`${p.party_name} · Remaining ${TF.money(TF.num(p.amount_due)-TF.num(p.amount_paid))}`;TF.$('payPayableAmount').value=(TF.num(p.amount_due)-TF.num(p.amount_paid)).toFixed(2);TF.$('payPayableNotes').value='';TF.$('payPayableDialog').showModal();}
  async function pay(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const {error}=await TF.state.supa.rpc('pay_payable_v5',{p_payable_id:TF.$('payPayableId').value,p_payment_date:TF.$('payPayableDate').value,p_amount:TF.num(TF.$('payPayableAmount').value),p_cash_account_id:TF.$('payPayableAccount').value,p_notes:TF.$('payPayableNotes').value.trim()});if(error)throw error;TF.$('payPayableDialog').close();TF.toast('Payable payment recorded');await load();}catch(err){TF.fail(err,'Payment not saved');}finally{TF.setLoading(b,false);}}
  TF.ready.then(()=>{fill();TF.$('fabricPurchaseForm').addEventListener('submit',saveFabric);TF.$('ownBatchForm').addEventListener('submit',own);TF.$('pulloutForm').addEventListener('submit',pullout);TF.$('subconForm').addEventListener('submit',subcon);['pulloutQty','pulloutSewerRate','pulloutPaid','subconQty','subconPrice','subconHandling','subconPaid'].forEach(id=>TF.$(id).addEventListener('input',()=>{updatePaymentFields();updateSummaries();}));TF.$('payablesTable').addEventListener('click',e=>{const b=e.target.closest('[data-pay]');if(b)openPay(b.dataset.pay);});TF.$('payPayableForm').addEventListener('submit',pay);TF.$('closePayableDialog').addEventListener('click',()=>TF.$('payPayableDialog').close());TF.$('cancelPayableDialog').addEventListener('click',()=>TF.$('payPayableDialog').close());window.addEventListener('twofly:refresh',load);load();}).catch(e=>TF.fail(e,'Production failed'));
})();
