(() => {
  'use strict';
  const TF=window.TwoFly; let plans=[],payments=[];
  const fmt=v=>TF.money(TF.num(v)); const date=v=>v?String(v).slice(0,10):'—';
  function monthBounds(d=new Date()){const y=d.getFullYear(),m=d.getMonth();return{start:`${y}-${String(m+1).padStart(2,'0')}-01`,end:new Date(y,m+1,0).toISOString().slice(0,10)};}
  function weekBounds(d=new Date(),priorOnMonday=false){const base=new Date(d);if(priorOnMonday&&base.getDay()===1)base.setDate(base.getDate()-1);const day=base.getDay(),diff=(day+6)%7;const s=new Date(base);s.setDate(base.getDate()-diff);const e=new Date(s);e.setDate(s.getDate()+6);return{start:s.toISOString().slice(0,10),end:e.toISOString().slice(0,10)};}
  function semiBounds(d=new Date()){const y=d.getFullYear(),m=d.getMonth(),day=d.getDate();if(day<=15)return{start:`${y}-${String(m+1).padStart(2,'0')}-01`,end:`${y}-${String(m+1).padStart(2,'0')}-15`};return{start:`${y}-${String(m+1).padStart(2,'0')}-16`,end:new Date(y,m+1,0).toISOString().slice(0,10)};}
  async function load(){try{const [a,b]=await Promise.all([TF.state.supa.from('v_staff_compensation_v13').select('*').order('name'),TF.state.supa.from('staff_payments_v13').select('*,staff_compensation_plans_v13(plan_name,pay_type,amount,staff_members_v13(name,role_title)),cash_accounts(name)').order('payment_date',{ascending:false})]);if(a.error||b.error)throw a.error||b.error;plans=a.data||[];payments=b.data||[];render();fillPlans();}catch(e){TF.fail(e,'Team & Payroll failed');}}
  function periodForPlan(p){return p.frequency==='weekly'?weekBounds(new Date(),p.due_rule==='sunday_or_monday'):p.frequency==='semi_monthly'?semiBounds():monthBounds();}
  function periodPaid(p,bounds){return payments.filter(x=>x.compensation_plan_id===p.compensation_plan_id&&date(x.period_start)===bounds.start&&date(x.period_end)===bounds.end).reduce((a,x)=>a+TF.num(x.amount),0);}
  function dueLabel(p,bounds){
    if(p.frequency==='monthly')return `Due ${bounds.end}`;
    if(p.frequency==='semi_monthly'){const d=new Date();if(d.getDate()<=15)return `Due ${bounds.end}`;const due=Number(String(bounds.end).slice(8,10))<30?bounds.end:`${String(bounds.end).slice(0,8)}30`;return `Due ${due}`;}
    return p.due_rule==='sunday_or_monday'?`Pay Sunday or Monday · period ends ${bounds.end}`:`Weekly · period ends ${bounds.end}`;
  }
  function render(){
    const current=TF.today().slice(0,7);const staff=new Set(plans.map(x=>x.staff_member_id));
    const monthly=plans.filter(x=>x.pay_type==='salary').reduce((sum,x)=>sum+(x.frequency==='monthly'?TF.num(x.amount):x.frequency==='semi_monthly'?TF.num(x.amount)*2:0),0);
    const weekly=plans.filter(x=>x.frequency==='weekly').reduce((sum,x)=>sum+TF.num(x.amount),0);
    const paidMonth=payments.filter(x=>String(x.payment_date).startsWith(current)).reduce((sum,x)=>sum+TF.num(x.amount),0);
    TF.$('kpiStaff').textContent=staff.size;TF.$('kpiMonthly').textContent=fmt(monthly);TF.$('kpiWeekly').textContent=fmt(weekly);TF.$('kpiPaidMonth').textContent=fmt(paidMonth);
    const groups=[...staff].map(id=>plans.filter(x=>x.staff_member_id===id));
    TF.$('staffCards').innerHTML=groups.map(g=>{const x=g[0];return `<article class="card ops-staff-card"><div class="card-body"><div class="ops-staff-head"><div><h3>${TF.esc(x.name)}</h3><p>${TF.esc(x.role_title)}</p></div><span class="pill ok">Active</span></div><p class="muted">${TF.esc(x.responsibilities)}</p><div class="ops-plan-list">${g.map(p=>{const bounds=periodForPlan(p),paid=periodPaid(p,bounds),remaining=Math.max(TF.num(p.amount)-paid,0);return `<div><span>${TF.esc(p.plan_name)}</span><strong>${fmt(p.amount)} · ${TF.esc(p.frequency.replace('_',' '))}</strong><small>${TF.esc(dueLabel(p,bounds))}</small><small>${remaining<=.01?'Current period: paid':`Current period remaining: ${fmt(remaining)}`}</small></div>`}).join('')}</div></div></article>`}).join('');
    TF.$('payrollTable').innerHTML=`<table><thead><tr><th>Paid</th><th>Employee / plan</th><th>Pay period</th><th>Amount</th><th>Account</th><th>Reference / notes</th></tr></thead><tbody>${payments.map(p=>{const plan=p.staff_compensation_plans_v13;return `<tr><td>${date(p.payment_date)}</td><td><strong>${TF.esc(plan?.staff_members_v13?.name||'')}</strong><br><small>${TF.esc(plan?.plan_name||'')}</small></td><td>${date(p.period_start)} to ${date(p.period_end)}</td><td><strong>${fmt(p.amount)}</strong></td><td>${TF.esc(p.cash_accounts?.name||'')}</td><td>${TF.esc(p.reference_number||p.notes||'')}</td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No payroll payments yet.</td></tr>'}</tbody></table>`;
  }
  function fillPlans(){TF.$('payrollPlan').innerHTML='<option value="">Select employee and plan</option>'+plans.map(p=>`<option value="${p.compensation_plan_id}">${TF.esc(p.name)} — ${TF.esc(p.plan_name)} — ${fmt(p.amount)}</option>`).join('');}
  function updatePeriod(){const p=plans.find(x=>x.compensation_plan_id===TF.$('payrollPlan').value);if(!p){TF.$('payrollSummary').textContent='Select a plan.';return;}let bounds=periodForPlan(p);TF.$('payrollStart').value=bounds.start;TF.$('payrollEnd').value=bounds.end;TF.$('payrollAmount').value=TF.num(p.amount).toFixed(2);TF.$('payrollSummary').textContent=`${p.name} · ${p.plan_name} · ${fmt(p.amount)} · ${String(p.due_rule).replaceAll('_',' ')}`;}
  async function save(e){e.preventDefault();const b=e.submitter;TF.setLoading(b,true);try{const r=await TF.state.supa.rpc('record_staff_payment_v13',{p_compensation_plan_id:TF.$('payrollPlan').value,p_period_start:TF.$('payrollStart').value,p_period_end:TF.$('payrollEnd').value,p_payment_date:TF.$('payrollDate').value,p_amount:TF.num(TF.$('payrollAmount').value),p_cash_account_id:TF.$('payrollAccount').value,p_reference_number:TF.$('payrollReference').value.trim(),p_notes:TF.$('payrollNotes').value.trim()});if(r.error)throw r.error;TF.toast('Staff payment recorded');e.target.reset();init();await load();}catch(err){TF.fail(err,'Payroll payment failed');}finally{TF.setLoading(b,false);}}
  function init(){TF.$('payrollDate').value=TF.today();TF.$('payrollAccount').innerHTML=TF.accountOptions(false);const m=monthBounds();TF.$('payrollStart').value=m.start;TF.$('payrollEnd').value=m.end;}
  TF.ready.then(()=>{init();TF.$('payrollPlan').addEventListener('change',updatePeriod);TF.$('payrollForm').addEventListener('submit',save);window.addEventListener('twofly:refresh',load);load();}).catch(e=>TF.fail(e,'Team & Payroll failed'));
})();
